/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_albin_jmessage_message_CaptureMessage */

#ifndef _Included_fr_albin_jnetsend_message_CaptureMessage
#define _Included_fr_albin_jnetsend_message_CaptureMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_albin_jmessagesend_message_CaptureMessage
 * Method:    getMessageText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_fr_albin_jmessagesend_message_CaptureMessage_getMessageText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
